-- DO NOT EDIT THIS FILE
-- THIS IS SIMPLY A LIST OF CONSTANTS 
-- https://pastebin.com/HPg8pYwi
Controls = {
    INPUT_ENTER = 23,               -- F
    INPUT_VEH_EXIT = 75,            -- F
    INPUT_VEH_HORN = 86,            -- H
    INPUT_VEH_HEADLIGHT = 74,
    INPUT_VEH_CIN_CAM = 80,
    INPUT_VEH_NEXT_RADIO = 81,
    INPUT_VEH_PREV_RADIO = 82,

    INPUT_CONTEXT = 51,             -- E
    INPUT_CONTEXT_SECONDARY = 52,   -- Q
}
