-- DO NOT EDIT THIS FILE
-- THIS IS SIMPLY A LIST OF CONSTANTS 
-- https://pastebin.com/HPg8pYwi
Controls = {
    INPUT_ENTER = 23,               -- F
    INPUT_VEH_EXIT = 75,            -- F
    INPUT_VEH_HORN = 86,            -- H

    INPUT_CONTEXT = 51,             -- E
    INPUT_CONTEXT_SECONDARY = 52,   -- Q
}
