-- DO NOT EDIT THIS FILE
-- THIS IS SIMPLY A LIST OF CONSTANTS 
-- https://pastebin.com/HPg8pYwi
Controls = {
    INPUT_ENTER = 23,               -- F
    INPUT_VEH_EXIT = 75,            -- F
    INPUT_VEH_HORN = 86,            -- H
    INPUT_VEH_HEADLIGHT = 74,
    INPUT_VEH_CIN_CAM = 80,
    INPUT_VEH_NEXT_RADIO = 81,
    INPUT_VEH_PREV_RADIO = 82,
    INPUT_VEH_ACCELERATE = 71,
    INPUT_VEH_BRAKE = 72,
    

    INPUT_CONTEXT = 51,             -- E
    INPUT_CONTEXT_SECONDARY = 52,   -- Q
}

-- Simple list of blip colors
BlipColor = {
    Default = 0,
    Red = 1,
    Green = 2,
    Blue = 3,
    White = 4,
    TaxiYellow = 5,
    LightRed = 6,
    Violet = 7,
    Pink = 8,
    LightOrange = 9,
    LightBrown = 10,
    LightGreen = 11,
    Teal = 12,
    VeryLightPurple = 13,
    DarkPurple = 14,
    Cyan = 15,
    LightYellow = 16,
    Orange = 17,
    LightBlue = 18,
    DarkPink = 19,
    DarkYellow = 20,
    DarkOrange = 21,
    LightGray = 22,
    LightPink = 23,
    LemonGreen = 24,
    ForestGreen = 25,
    ElectricBlue = 26,
    BrightPurple = 27,
    DarkTaxiYellow = 28,
    DarkBlue = 29,
    DarkCyan = 30,
    -- LightBrown = 31,
    VeryLightBlue = 32,
    -- LightYellow = 33,
    -- LightPink = 34,
    -- LightRed = 35,
    -- LightYellow = 36,
    -- White = 37,
    -- Blue = 38,
    -- LightGray = 39,
    DarkGray = 40,
}